version: '3'

services:
  test-oidc:
    image:  endimion13/grids-test-custodian:0.0.1
    environment:
      ISSUER_URL: https://dss1.aegean.gr/auth/realms/kyb
      OIDC_CLIENT_ID: kompany-3
      OIDC_CLIENT_SECRET: d5980dda-512b-4986-afa1-90293adb6b59
      OIDC_REDIRECT_URI: http://dss.aegean.gr:3030/callback
    ports:
      - 3030:3000
